{% set name = "itango" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a029953e3c8224d3e9e72249b01facec6d251bed7d05cd0df90930c1033cd924

build:
  number: 0
  noarch: python
  entry_points:
    - itango = itango:run
    - itango3 = itango:run
    - itango-qt = itango:run_qt
    - itango3-qt = itango:run_qt
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - pytango >=9.2.0
    - ipython >=1.0
    - packaging

test:
  imports:
    - itango
  commands:
    - itango --help
    - itango3 --help

about:
  home: https://gitlab.com/tango-controls/itango
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: An interactive Tango client
  description: |
    ITango is a PyTango CLI based on IPython.
    It is designed to be used as an IPython profile.
  dev_url: https://gitlab.com/tango-controls/itango
  doc_url: https://itango.readthedocs.io/

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
