{% set name = "itango" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cacdded1ff9f1928dc1b53b8f135d43d60f20baf510c71813be589562339b7d

build:
  number: 0
  noarch: python
  entry_points:
    - itango = itango:run
    - itango3 = itango:run
    - itango-qt = itango:run_qt
    - itango3-qt = itango:run_qt
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pytango >=9.2.0
    - ipython >=4.0
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - itango
  commands:
    - itango --help
    - itango3 --help

about:
  home: https://gitlab.com/tango-controls/itango
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: An interactive Tango client
  description: |
    ITango is a PyTango CLI based on IPython.
    It is designed to be used as an IPython profile.
  dev_url: https://gitlab.com/tango-controls/itango
  doc_url: https://itango.readthedocs.io/

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
