{% set name = "itango" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1409cff2814f2945d2848c3c2777e5ed8ae5f45c6f16380abafcb9b5f3fed9d8

build:
  number: 0
  noarch: python
  entry_points:
    - itango = itango:run
    - itango3 = itango:run
    - itango-qt = itango:run_qt
    - itango3-qt = itango:run_qt
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77.0.3
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pytango >=9.3.0
    - ipython >=8.5,<10.0
    - packaging

test:
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pytest
    - gevent
    - tango-test
  imports:
    - itango
  commands:
    - itango --help
    - itango3 --help
    - pytest -v tests

about:
  home: https://gitlab.com/tango-controls/itango
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: An interactive Tango client
  description: |
    ITango is a PyTango CLI based on IPython.
    It is designed to be used as an IPython profile.
  dev_url: https://gitlab.com/tango-controls/itango
  doc_url: https://itango.readthedocs.io/

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
